blank_issues_enabled: false
contact_links:
  - name: OpenKore forums
    url: https://forums.openkore.com/
    about: Please ask and answer questions here in our forum.
  - name: OpenKore Discord
    url: https://discord.gg/X7SNfMXBJ5
    about: Chat with us in the Discord support channel.
