# workflow syntax           https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# runs-on                   https://github.com/actions/virtual-environments
# setup-python              https://github.com/actions/setup-python
# actions-setup-perl        https://github.com/marketplace/actions/setup-perl-environment
# strawberry Perl 5.12.3.0  https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip
# strawberry Perl 5.32.1.1  https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip
# actions-upload-artifact   https://github.com/actions/upload-artifact
# actions-download-artifact https://github.com/actions/download-artifact
# actions-cache             https://github.com/actions/cache

name: Build Win
on:
  push:
    branches:
  pull_request:

jobs:
  build_XSTools:

    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}, perl ${{ matrix.perl }}) ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2016
          python: 2.7
          architecture: x86
          perl: 5.12
          strawberry_distr: 'https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip'

        - os: windows-latest
          python: 3
          architecture: x86
          perl: 5.32
          strawberry_distr: 'https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip'

    steps:
    - name: GIT checkout
      uses: actions/checkout@v2

    # setup matrix:
    # - windows-2016 + python 2.7 x86 + strawberry perl 5.12 x86 + strawberry g++ x86
    # - windows-2019 + python 3   x86 + strawberry perl 5.32 x86 + strawberry g++ x86
    - name: setup-python ${{ matrix.python }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: set path
      shell: cmd
      run: |
        set path
        where perl
        where gmake

    - name: Удаляем дефолтовый Strawberry и g++
      shell: bash
      run: |
        echo -e "\e[34m# rm -rf /c/Strawberry/*"
        echo -e "\e[34mmv /c/Strawberry/* /c/Temp/"
        rm -rf /c/Strawberry/*
        ls -lh /c/
        echo -e "\e[34m== remove g++ x64"
        echo -e "\e[34m# rm -f /c/ProgramData/Chocolatey/bin/g++.exe"
        rm -f /c/ProgramData/Chocolatey/bin/g++.exe
        echo -e "\e[34m# du -sh /c/Strawberry/"
        du -sh /c/Strawberry/

    #- name: du -sh $GITHUB_WORKSPACE
    #  shell: bash
    #  run: du -sh $GITHUB_WORKSPACE

    - name: set path
      shell: cmd
      run: |
        set path
        where perl
        where gmake
        dir c:\Strawberry

    - name: Check the Strawberry cache
      if: runner.os == 'Windows'
      id: cache-strawberry
      uses: actions/cache@v2
      with:
        path: c:\Strawberry
        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}_4

    #- name: du -sh $GITHUB_WORKSPACE
    #  shell: bash
    #  run: du -sh $GITHUB_WORKSPACE

    - name: set path
      shell: cmd
      run: |
        set path
        where perl
        where gmake

    - name: Replace perl to ${{ matrix.perl }} ${{ matrix.architecture }}
      if: runner.os == 'Windows' && steps.cache-strawberry.outputs.cache-hit != 'true'
      run: |
        echo "Кеш НЕ найден"
        echo "================================================================="
        echo "== previous version of Perl:"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== remove the default perl"
        echo "================================================================="
        rm -r C:/Strawberry/*
        echo "================================================================="
        echo "== download strawberry perl ${{ matrix.perl }} ${{ matrix.architecture }}"
        echo "================================================================="
        Invoke-WebRequest ${{ matrix.strawberry_distr }} -OutFile strawberry.zip
        echo "================================================================="
        echo "== РАСПАКОВЫВАЕМ strawberry-perl"
        echo "================================================================="
        7z.exe x strawberry.zip -o"C:/Strawberry"
        rm strawberry.zip
        echo "================================================================="
        echo "== a new version of Perl:"
        echo "================================================================="
        perl --version

    - name: set path
      shell: cmd
      run: |
        set path
        where perl
        where gmake

    - name: Environment check
      shell: bash
      run: |
        which perl
        echo -e "\e[34m# du -sh /c/Strawberry/"
        du -sh /c/Strawberry/
        echo -e "\e[34m# ls -lh /c/Strawberry/"
        ls -lh /c/Strawberry/
        echo -e "\e[34m# /c/Strawberry/perl/bin/perl.exe -v"
        /c/Strawberry/perl/bin/perl.exe -v
        echo -e "\e[34m== python version check:"
        python -V
        echo -e "\e[34m======================"
        echo -e "\e[34m== perl version check:"
        perl --version
        echo -e "\e[34m== perl version check:"
        perl --version
        echo -e "\e[34m== perl version check:"
        perl --version
        echo -e "\e[34m== perl version check:"
        perl --version
        echo -e "\e[34m== perl version check:"
        perl --version
        echo -e "\e[34m======================"
        echo -e "\e[34m== Time::HiRes module:"
        perl -e "use Time::HiRes;"
        if  [ $? == 0 ] ; then echo -e "\e[34mOK"; fi
        echo -e "\e[34m========================="
        echo -e "\e[34m== Compress::Zlib module:"
        perl -e "use Compress::Zlib;"
        if  [ $? == 0 ] ; then echo -e "\e[34mOK"; fi
        echo -e "\e[34m====================="
        echo -e "\e[34m== g++ version check:"
        g++ --version
        echo -e "\e[34m======================="
        echo -e "\e[34m== gmake version check:"
        gmake --version
        echo -e "\e[34m======================="
        perl -V

    - name: ВЕРСИИ g++
      shell: cmd
      run: |
        set path
        where perl
        where gmake
        echo "==================="
        g++ --version
        #make --version
        gmake --version
        g++ -v
        #rm -r c:\msys64\*
        g++ --version
        #make --version
        gmake --version
        g++ -v

    - name: Run make XSTools.dll
      run: |
        perl --version
        gmake all
        echo "================================================================="
        ls src\auto\XSTools\XSTools.dll
        ls src\auto\XSTools\NetRedirect.dll

    - name: Making artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_perl${{ matrix.perl }}${{ matrix.architecture }}
        path: |
          src\auto\XSTools\XSTools.dll
          src\auto\XSTools\NetRedirect.dll


  make_test:

    name: make test ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }})
    needs: build_XSTools
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2016
          python: 2.7
          architecture: x86
          perl: 5.12

        - os: windows-latest
          python: 3
          architecture: x86
          perl: 5.32

    steps:
    - name: GIT checkout
      uses: actions/checkout@v2

    - name: Удаляем дефолтовый Strawberry
      shell: bash
      run: |
        echo -e "\e[34m# rm -rf /c/Strawberry/*"
        mv /c/Strawberry/* /c/Temp/
        rm -f /c/ProgramData/Chocolatey/bin/g++.exe
        echo -e "\e[34m# ls -l *.dll"
        ls -l *.dll
        echo -e "\e[34m# rm -f *.dll"
        rm -f *.dll
        echo -e "\e[34m# du -sh /c/Strawberry/"
        du -sh /c/Strawberry/

    #- name: du -sh $GITHUB_WORKSPACE
    #  shell: bash
    #  run: du -sh $GITHUB_WORKSPACE

    - name: Check the Strawberry cache
      id: cache-strawberry
      if: runner.os == 'Windows'
      uses: actions/cache@v2
      with:
        path: c:\Strawberry
        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}_4

    #- name: du -sh $GITHUB_WORKSPACE
    #  shell: bash
    #  run: du -sh $GITHUB_WORKSPACE

    - name: Display an error if the cache is found
      if: runner.os == 'Windows' && steps.cache-strawberry.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo -e "\e[30;41mcache-strawberry НЕ найден!!! Смотри шаг 'Post Check the Strawberry cache' в предыдущем джобе."
        exit 1

    - name: Environment check
      shell: bash
      run: |
        echo -e "\e[34m# du -sh /c/Strawberry/"
        du -sh /c/Strawberry/
        echo -e "\e[34m== perl version check:"
        perl --version
        echo -e "\e[34m======================="
        perl -V

    - name: Восстанавливаем артифакт
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.os }}_perl${{ matrix.perl }}${{ matrix.architecture }}

    - name: Проверяем наличие артифакта (XSTools)
      shell: bash
      run: |
        echo -e "\e[34m# ls -lh | grep XSTools"
        ls -lh | grep XSTools
        echo -e "\e[34m# mv XSTools.dll ./src/test/"
        mv XSTools.dll ./src/test/
        echo -e "\e[34m# ls -lh ./src/test/ | grep XSTools"
        ls -lh ./src/test/ | grep XSTools

    - name: переменные
      shell: bash
      run: |
        pwd
        echo "== GITHUB_WORKSPACE"
        echo $GITHUB_WORKSPACE
        echo "== pwd"
        pwd
        echo "== ls -l"
        ls -l
        echo "== du -sh openkore"
        du -sh /d/a/openkore/openkore
        echo ================= /d
        ls -l /d
        echo ================= /d/a
        ls -l /d/a
        echo ================= /d/a/_temp
        ls -l /d/a/_temp

    - name: Run Tests
      run: |
        cat .\Makefile
        echo "==============================================="
        gmake test