# runs-on:            https://github.com/actions/virtual-environments
# setup-python:       https://github.com/actions/setup-python
# actions-setup-perl: https://github.com/marketplace/actions/setup-perl-environment

name: Build XSTools
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build_XSTools:

    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2016
          python: 2.7
          architecture: x86
          perl: 5.12

        - os: windows-2016
          python: 3
          architecture: x86
          perl: 5.32

        - os: windows-latest
          python: 3
          architecture: x86
          perl: 5.32

        - os: ubuntu-18.04
          python: 2.7
          architecture: x64
          perl: 5.12

        - os: ubuntu-latest
          python: 3
          architecture: x64
          perl: latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # setup Windows matrix: python 2.7_x86, 3_x86 and strawberry perl 5.12_x86, 5.32_x86
    # setup Linux   matrix: python 2.7_x64, 3_x64 and perl 5.12_x64, last_x64
    - name: setup-python ${{ matrix.python }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: setup-perl ${{ matrix.perl }}
      uses: shogo82148/actions-setup-perl@v1
      if: runner.os == 'Linux'
      with:
        perl-version: ${{ matrix.perl }}

    - name: Replace perl to 5.12.3.0 x86
      if: runner.os == 'Windows' && matrix.perl == '5.12'
      run: |
        rm -r C:/Strawberry/*
        Invoke-WebRequest https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0.zip -OutFile strawberry.zip
        7z.exe x strawberry.zip -o"C:/Strawberry"

    - name: Replace perl to 5.32.1.1 x86
      if: runner.os == 'Windows' && matrix.perl == '5.32'
      run: |
        rm -r C:/Strawberry/*
        Invoke-WebRequest https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip  -OutFile strawberry.zip
        7z.exe x strawberry.zip -o"C:/Strawberry"

    - name: Environment check
      run: |
        echo "------------- check g++ version -------------"
        g++ --version
        echo "------------- perl version -------------"
        perl --version
        echo "------------- Time::HiRes module -------------"
        perl -e "use Time::HiRes;"
        echo "------------- Compress::Zlib module -------------"
        perl -e "use Compress::Zlib;"
        echo "------------- python version -------------"
        python -V

    - name: Run make XSTools.dll
      if: runner.os == 'Windows'
      run: |
        make all
        echo "================================================================="
        echo "DONE:"
        dir src\auto\XSTools\ | findstr "dll"

    - name: Run make XSTools.so
      if: runner.os == 'Linux'
      run: |
        sudo apt install -y libreadline6-dev libcurl4-openssl-dev
        make all
        echo "======================================================"
        echo "DONE:"
        ls -l src/auto/XSTools/ | grep so